CREATE TABLE [dbo].[Bestuurder] (
    [bestuurderid]        INT            IDENTITY (1, 1) NOT NULL,
    [adresid]             INT            NULL,
    [voornaam]            NVARCHAR (150)  NOT NULL,
    [achternaam]          NVARCHAR (150)  NOT NULL,
    [geboortedatum]       NVARCHAR (150)  NOT NULL,
    [rijksregisternummer] NVARCHAR (25)  NOT NULL,
    [rijbewijstype]       NVARCHAR (150) NOT NULL,
    [aanmaakdatum]        DATE      NULL,
    [voertuigid]          INT       NULL,
    PRIMARY KEY CLUSTERED ([bestuurderid] ASC),
    UNIQUE NONCLUSTERED ([rijksregisternummer] ASC),
    CONSTRAINT [FK_Table_Adres] FOREIGN KEY ([adresid]) REFERENCES [dbo].[Adres] ([adresid]),
    CONSTRAINT [FK_Bestuurder_Voertuig] FOREIGN KEY ([voertuigid]) REFERENCES [dbo].[Voertuig] ([voertuigid]), 
);
