CREATE TABLE [dbo].[Voertuig] (
    [voertuigid]      INT           IDENTITY (1, 1) NOT NULL,
    [automodelid]     INT           NOT NULL,
    [brandstoftypeid] INT           NOT NULL,
    [hybride]         BIT           NOT NULL,
    [kleurnaam]       NVARCHAR (150) NULL,
    [aantal_deuren]   NVARCHAR (25)  NULL,
    [chassisnummer]   NVARCHAR (25) NOT NULL,
    [nummerplaat]     NVARCHAR (25)  NOT NULL,
    [inboekdatum]     DATE    NULL,
    PRIMARY KEY CLUSTERED ([voertuigid] ASC),
    UNIQUE NONCLUSTERED ([nummerplaat] ASC),
    UNIQUE NONCLUSTERED ([chassisnummer] ASC),
    CONSTRAINT [FK_Voertuig_automodel] FOREIGN KEY ([automodelid]) REFERENCES [dbo].[Automodel] ([automodelid]),
    CONSTRAINT [FK_Voertuig_Brandstoftype] FOREIGN KEY ([brandstoftypeid]) REFERENCES [dbo].[Brandstoftype] ([brandstoftypeid]),
);